"""relation migration

Revision ID: 340aeb769d76
Revises: 57f6dac20634
Create Date: 2025-05-17 00:42:37.246380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '340aeb769d76'
down_revision: Union[str, None] = '57f6dac20634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_executors',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('task_observers',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.add_column('departments', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('departments', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'companies', ['company_id'], ['id'])
    op.add_column('invites', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'invites', 'companies', ['company_id'], ['id'])
    op.add_column('positions', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_position_in_company', 'positions', ['name', 'company_id'])
    op.create_foreign_key(None, 'positions', 'companies', ['company_id'], ['id'])
    op.add_column('role_assignments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('role_assignments', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'role_assignments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'role_assignments', 'departments', ['department_id'], ['id'])
    op.add_column('tasks', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('responsible_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['responsible_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['author_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('position_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'position_id')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'responsible_id')
    op.drop_column('tasks', 'author_id')
    op.drop_constraint(None, 'role_assignments', type_='foreignkey')
    op.drop_constraint(None, 'role_assignments', type_='foreignkey')
    op.drop_column('role_assignments', 'department_id')
    op.drop_column('role_assignments', 'user_id')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint('unique_position_in_company', 'positions', type_='unique')
    op.drop_column('positions', 'company_id')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_column('invites', 'company_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'manager_id')
    op.drop_column('departments', 'company_id')
    op.drop_table('task_observers')
    op.drop_table('task_executors')
    # ### end Alembic commands ###
