"""renamed invite column

Revision ID: eaba36dcee8c
Revises: 340aeb769d76
Create Date: 2025-05-17 01:14:53.920815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaba36dcee8c'
down_revision: Union[str, None] = '340aeb769d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.drop_column('invites', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('invites', 'is_used')
    # ### end Alembic commands ###
